[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
print_me = { path = "../print_me" }
print_me_derive = { path = "../print_me/print_me_derive" }